import Link from "next/link";
import '../../styles/pages/admin.css';

export const metadata = {
  title: 'Emmas Studio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header><Link href="/" className="back-link">&#8630; DIYEmma.com</Link></header>
        {children}
      </body>
    </html>
  )
}
